# Generated by Django 3.2.6 on 2021-08-29 16:27

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210829_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, max_length=100, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
